# Generated by Django 4.2.7 on 2023-11-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('isAllowed', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('_from', models.IntegerField()),
                ('to', models.IntegerField()),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationAsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='defuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formteacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('clazz', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('children', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.CharField(max_length=5)),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacheableSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('english', models.BooleanField(default=0)),
                ('german', models.BooleanField(default=0)),
                ('literature', models.BooleanField(default=0)),
                ('mathematics', models.BooleanField(default=0)),
                ('history', models.BooleanField(default=0)),
                ('arts', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachersOfClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('clazz', models.CharField(max_length=5)),
            ],
        ),
    ]
